### PR TITLE
Added new method main awards

### PR DESCRIPTION
**Pull request by duck7000**
This method get only the awards info at the title page inside the yellow block.
I made this because this is a simple version for if you only want this info instead of all awards (witch can be a lot of information)

It may be useful to others as well.

### CODE REVIEW

**Comment by duck7000** [comment]
I'm aware that this needs a test, there never was one so i will, in time, to figure something out

**Comment by duck7000** [comment]
I will make a test but after this is reviewed and accepted

**Comment by duck7000** [comment]
I assume that there is no interest in this new method.
If someone do report to this PR

If no response i will close this as it has no point if no one is interested.
no harm feelings here

**Comment by Thomasdouscha** [comment]
it is interesting to me. I can test it. But give me the files than i will do it.

**Comment by Thomasdouscha** [comment]
1.test [tt0068646](http://www.imdb.com/title/tt0068646)    {"awards":"Won 3 Oscars","wins":"31","nominations":"30"}
2.test [tt0120338](http://www.imdb.com/title/tt0120338)    {"awards":"Won 11 Oscars","wins":"125","nominations":"83"}
3.test [tt5034838](http://www.imdb.com/title/tt5034838)    {"awards":"","wins":"2","nominations":"14"}
4.test  [tt6156584](http://www.imdb.com/title/tt6156584)    {"awards":"","wins":"4","nominations":"22"}
5.test  [tt2560140](http://www.imdb.com/title/tt2560140)    empty

It works quite well.

**Comment by duck7000** [comment]
Okay that is nice to here you have interest and that it works.

I'm not sure @tboothman will merge this though, it means another extra method to maintain but if necessary i will do the maintenance

**Comment by Thomasdouscha** [comment]
I think he will merge it and it returns summarize info which exactly we needed. 
Thanks a lot @duck7000 ! Good job!

**Comment by Thomasdouscha** [comment]
@tboothman please let you merge it. Of course it is your call!

**Comment by duck7000** [comment]
@tboothman , @jreklund 
Last try, can/will you merge this or not?

**Comment by Thomasdouscha** [comment]
It was working in my tests.

**Pull request closed without merging**
