### PR TITLE
Lint the project + other tiny updates

### PR DESCRIPTION
**Pull request by X-Coder264**
Now that the minimum version of PHP has been bumped to 5.6 some new doors opened :) I added a linter so that the entire codebase is PSR-2 compliant and I updated PHPUnit and Mockery dependencies.

### CODE REVIEW

**Comment by X-Coder264** [comment]
ping @tboothman @jreklund

**Comment by jreklund** [comment]
It have only been 3(!) days and you made +7,343 code changes. It takes time to look at what you did.
But at first glance there are some html code that uses 2 spaces instead of 4.

**Comment by X-Coder264** [comment]
Sorry, I didn't ping you in a "you have to merge this immediately" way, I just wanted to hear some kind of feedback and/or to check if this was even considered as something that has a chance of being merged :)

**Comment by jreklund** [comment]
No worries. Personally I have little to none experience even with Composer. I don't even touch all these extra stuffs. So can't say if it's good or bad to include more packages. PSR-2 are good thought.

I just fix broken functions and write tests. :-)

Lint tries to clean up the code automatic and will forcefully change your code correct? Demo aren't really required but should follow the same standard. Then I re-wrote it I followed the old "standard" with 2 spaces.

**Comment by X-Coder264** [comment]
The cs-fixer is only a dev dependency so any project requiring this package won't get the linter with it so there's no problem there.

> Lint tries to clean up the code automatic and will forcefully change your code correct?

Yes, you just write the rules how you want your code to be formatted and then you just run the linting command and in a few seconds the entire codebase gets changed/linted according to the rules that you specify.

**Comment by tboothman** [comment]
I don't think it was likely either of us were going to read 7000 lines of changed code by someone who's not contributed to the project before, but thanks for the prod on this.
The formatting was pretty weird in this project but and I've now reformatted it all to psr-2.

**Pull request closed without merging**
