### PR TITLE
Multiple function fixed and tests created

### PR DESCRIPTION
**Pull request by jreklund**
I have fixed a couple of function when I wrote some new tests. But I haven't found the use for the second if/elseif in comment_split.

```php
public function comment_split() {
if (empty($this->split_comment)) {
  if ($this->main_comment == "") $comm = $this->comment();
  if (@preg_match('!<strong[^>]*>(.*?)</strong>.*?<div class="comment-meta">\s*(.*?)\s*\|\s*by\s*(.*?</a>).*?<p[^>]*>(.*?)\s*</div!ims',$this->main_comment,$match)) {
    @preg_match('!href="(.*?)"[^>]*><span[^>]*>(.*)</span!i',$match[3],$author);
    $this->split_comment = array("title"=>$match[1],"date"=>$match[2],"author"=>array("url"=>$author[1],"name"=>$author[2]),"comment"=>trim($match[4]));
  } elseif (@preg_match('!<div class="comment-meta">\s*<meta itemprop="datePublished" content=".+?">\s*(.{10,20})\s*\|\s*by\s*(.*?)\s*&ndash;.*?<div>\s*(.*?)\s*</div>!ims',$this->main_comment,$match)) {
    @preg_match('!href="(.*?)">(.*)</a!i',$match[2],$author);
    $this->split_comment = array('title'=>'','date'=>$match[1],'author'=>array("url"=>$author[1],"name"=>$author[2]),"comment"=>trim($match[3]));
  }
}
return $this->split_comment;
}
```
Haven't found a page that uses this one. But I left it unaltered in case we find one.
```php
  } elseif (@preg_match('!<div class="comment-meta">\s*<meta itemprop="datePublished" content=".+?">\s*(.{10,20})\s*\|\s*by\s*(.*?)\s*&ndash;.*?<div>\s*(.*?)\s*</div>!ims',$this->main_comment,$match)) {
    @preg_match('!href="(.*?)">(.*)</a!i',$match[2],$author);
    $this->split_comment = array('title'=>'','date'=>$match[1],'author'=>array("url"=>$author[1],"name"=>$author[2]),"comment"=>trim($match[3]));
  }
```

EDIT: Some of the tests failed when I deleted the cache and made a clean tests. Will look at them again.

### CODE REVIEW

**Comment by tboothman** [comment]
There's quite a few mysteries in some of the functions unfortunately. Like why is yearspan() even a function? There are already two functions that return the data it does. Who even knows what that regular expression in it does... it implies you could have an endyear of '????'

**Comment by tboothman** [comment]
Thanks for this. I'll merge it in

**Comment by jreklund** [comment]
Back in the old days, IMDb had ???? on some TV-shows instead of " ", like now.
The regex for yearspan is obsolete, not that I look at it:
 `!<title>.*?\(.*?(\d{4})(–|-)(\d{4}|\?{4}).*?</title>!i` With ???? just in case. ;-)

Will not make a pull request for that, due to the fact it's working by falling back to year() and yearend(). So I think we should just remove the regex and return year() and yearend(). So we only have to worry about title_year().

**Comment by tboothman** [comment]
Whoops. Thought I merged this before

**Pull request merged**
