### PR TITLE
plot_split filter

### PR DESCRIPTION
**Pull request by duck7000**
- Add filter to get rid of {, <, etc. it interferes with smarty framework for example.
And no it does not look like to just filter out  those character by itself, it is often a combination.

### CODE REVIEW

**Comment by duck7000** [comment]
#209 to get the details.
The goal is to clean author name of unwanted characters that could interfere with, for example, Smarty framework because those frameworks often use {}

**Comment by jreklund** [comment]
Personally I don't think this is the right way to go. It sounds more that you have an XSS problem in your application due to the fact you aren't escaping any of the output from IMDb

**Comment by duck7000** [comment]
Mmm this sounds beyond my skills I'm afraid.
So you are saying that there is nothing wrong with this method, but the problem lies in my application?
The output of the author names do contain those characters though.

Any suggestions, or should i close this request?

**Comment by jreklund** [comment]
It may look odd that they have chosen to format it with <, ( or { but it's technically not wrong. Haven't checked their official style guide what the new format looks like. We don't have a style guide of our own, what to keep, what to remove etc.

Regarding Smarty, what you are looking for are [variable modifiers](https://www.smarty.net/docs/en/language.modifier.escape.tpl). Search for `smarty_modifier_escape` in Smarty in case you want to see what it actually does.

Example:
`{$split_plot[i]['author']['name']|escape}`

**Comment by duck7000** [comment]
Okay escape in smarty is a good idea.
And it is true that imdbphp  not should interfere with the output but in this case it is annoying i guess.
So what should we do in this case?
It remains odd that somebody at imdb fills in a email address what is surrounded by `{}`

**Comment by jreklund** [comment]
Escaping on output are a must, in case you don't want to get hacked.

Personally I would leave it as is, don't think the user them-self styled it as <email>, (email) or {email} rather IMDb did it for some odd reason. <email> are the "real one" in terms on how an email should be styled.

**Comment by duck7000** [comment]
agree, i close this request.
Thanks for your excellent comments!

**Pull request closed without merging**
