### PR TITLE
extract english title

### PR DESCRIPTION
**Pull request by M0H4MM4D0UTIS**
I need to extract the English title and I've used this code
Because origin_title (), title () does not specify which English title is

### CODE REVIEW

**Comment by tboothman** [comment]
As specified in the readme https://github.com/tboothman/imdbphp#configuration you set the language in the config and then title() is the title in the language you've chosen and orig_title() is the title in the language the film was made in

**Comment by tboothman** [comment]
What explanation would you have liked and where could it have been to make this clearer?
I think the explanation in the config class is pretty good https://github.com/tboothman/imdbphp/blob/master/src/Imdb/Config.php#L31
The explanation of what orig_title is could be made clearer https://github.com/tboothman/imdbphp/blob/master/src/Imdb/Title.php#L305 Would that have helped?

**Comment by M0H4MM4D0UTIS** [comment]
> As specified in the readme https://github.com/tboothman/imdbphp#configuration you set the language in the config and then title() is the title in the language you've chosen and orig_title() is the title in the language the film was made in

Does not work in new versions
So I tried to write another function

**Comment by jreklund** [comment]
Hi, could you give us a couple of titles (preferably their ID) in case there really should be English titles in origin_title(). Sometimes IMDb [geo-location](https://github.com/tboothman/imdbphp/blob/master/src/Imdb/Config.php#L123) kicks in before your preferred settings in `$language` and it dosen't matter how much you try to change it.

It will also be helpful to know where your server are hosted. And by where I mean country and not company. If it's your local machine, what country you live in.

**Pull request closed without merging**
