### PR TITLE
fix for filemtime(): stat failed error

### PR DESCRIPTION
**Pull request by sankam-nikolya**

### CODE REVIEW

**Comment by tboothman** [comment]
Surely you have some misconfiguration. It should only be trying to do that if you have config->storecache = true which also checks if the folder is writeable. Do you have a non writeable file in your cache folder?

**Comment by sankam-nikolya** [comment]
the directory is empty, rights 0777

**Comment by IzzySoft** [comment]
But your PR isn't fixing anything, it's just suppressing possible error messages. I'd be careful with such things and use them only rarely. I agree with Tom here: this code has been in there for years, and many people have used it. If there were an error in there, we'd heard of it before – so a misconfiguration is more likely.

We can't tell for sure, as we don't have the details (we'd need to look into your configuration, and need the name of the directory you *expect* being used) – but I'd suggest to double-check that.

**Comment by sankam-nikolya** [comment]
thx

**Pull request closed without merging**
