### PR TITLE
Fixed method parsearticles

### PR DESCRIPTION
**Pull request by duck7000**
This method was not working.
#259 reveals that the problem is in this method
I modified it al lot to get rid of at least one regular expression and easier to read

it also fixes these methods as well as they use this parsearticles() :
interviews(), articles(), pictorials(), magcovers()

I don't just understand why auturl and inturl are there?
I suspect for compatibility reasons but it doesn't make any sense to me

### CODE REVIEW

**Comment by duck7000** [comment]
@all can someone test this method so that we can assure it  now works properly?

**Comment by Thomasdouscha** [comment]
Actually i dont use these methods. But i am gonna try and test in weekend.

**Comment by duck7000** [comment]
Is this something that is still used by someone?
I fixed this but there seems no interest in it at all

**Comment by tboothman** [comment]
Could you add a test please for whatever it is that this is fixing. As far as I can see the only test that covers this method is `test_magcovers`. It passed before and it passes now which is great but then what are all the changes for? Some of it seems to be dealing with dates expressed as day month year, month year and year but I have no idea what the last half is doing.

I'd be fine with removing inturl and auturl as they've been empty strings since 2011. It looks like the publicity listings used to link somewhere.

**Comment by duck7000** [comment]
Wow i'm getting sick and tired of lax attitude here!
This pr is open since feb this year (that is almost 8 months later!) and this is the first time you even responded, and your response complains about what this is fixing? 
Well i suggest you start reading the issue again! 
The whole idea about my modifications is to deal with different formatting of dates, years etc and with the details part (the part you do not seems to understand)
And the original poster of that issue tested my fixes and confirms it works for his problem..

Even if i did made a test it would still not even been reviewed, now would it?

I have the feeling that the attitude of maintainers here is to sit and wait if someone complains about something isn't working, or if they self have a problem with imdbphp. At least @jreklund admits that he only commits to this repo if he has a problem in his own project.

This is de second time i explode like this and that will be the last one, i quit doing this any longer.

**Pull request closed without merging**
