### PR TITLE
Change geo-location

### PR DESCRIPTION
**Pull request by jreklund**
Sometimes your server aren't located in your preferred area (language), so you can use another ip address (preferred a public proxies), for tricking IMDb geo-location system.

### CODE REVIEW

**Comment by tboothman** [comment]
Can't you just set the accept-language header to get different countries' stuff?

**Comment by jreklund** [comment]
No, not at 100% success rating, if you want the "World-wide" country. After running `composer test` over and over again specifying `en-US`, `en-GB` and `en` in different orders. I never got it to change from `Det blåser upp en vind` (Swedish) into the correct test `The Wind Rises` (World-wide).

So accept-language never kicks in for the "World-wide" in "English mode". I get the correct tile if I specify Germany, Norway etc. So the only way to get "World-wide" is sitting behind a English/American IP-address and specify `en` or `en-US,en` or `en-GB,en`.


Kaze tachinu |   |   | original title
-- | -- | -- | --
Untitled Hayao Miyazaki Project |   |   |  
Se levanta el viento |   | Argentina |  
Le vent se lève |   | Belgium | French title
Вятърът се надига |   | Bulgaria | Bulgarian title
Vidas ao Vento |   | Brazil |  
Le vent se lève |   | Canada | French title
The Wind Rises |   | Canada | English title
Le vent se lève |   | Switzerland | French title
Se levanta el viento |   | Chile |  
Wie der Wind sich hebt |   | Germany |  
Når vinden rejser sig |   | Denmark |  
El vent s'eleva |   | Spain | Catalan title, complete title
El viento se levanta |   | Spain |  
Det blåser upp en vind |   | Finland | Swedish title
Tuuli nousee |   | Finland |  
Le vent se lève |   | France |  
Szél támad |   | Hungary |  
Ha'rouakh ha'ola |   | Israel | Hebrew title
Baad barmikhizad |   | Iran | Persian title
Si alza il vento |   | Italy |  
The Wind Has Risen |   | Japan | literal English title
The Wind Rises |   | Japan | English title
Se levanta el viento |   | Mexico |  
Feng qile |   | Malaysia | alternative title, Mandarin title
Vinden stiger |   | Norway |  
Zrywa sie wiatr |   | Poland |  
As Asas do Vento |   | Portugal |  
Uzletanje |   | Serbia |  
Beтер крепчает |   | Russia |  
Det blåser upp en vind |   | Sweden |  
Rüzgar Yükseliyor |   | Turkey | Turkish title
Вiтер дужчае |   | Ukraine |  
Se levanta el viento |   | World-wide | Spanish title
The Wind Rises |   | World-wide | English title

So it's this or change `title()` so that it checks for available `aka` and if it finds "World-wide (English title)" and you only want `en`, return it instead of what IMDb said.

**Comment by tboothman** [comment]
You mind resetting your master back to 4191be79279b301c6a2ec0674d6699d4ffef93b4 and i'll get this merged in.
This seemed a bit heavy handed at first and I doubt anyone will use it but if it helps you run the tests then that's good enough for me.

**Comment by jreklund** [comment]
I couldn't figure out how to delete 3263eae, so I pushed a new one 6266ac5 with the same information as the current function. Do you know the command to delete a single commit?

No idea how useful it will be for anyone else but me, but I sure hope I get all tests correct in the future or shame on me.

If you create an account at IMDb, you can change your language, but it dosen't set in inside a cookie, it stores it with your profile. So I couldn't steal anything from there.

**Pull request merged**
