### PR TITLE
Change recommendations back to html parsing. Remove year and votes

### PR DESCRIPTION
**Pull request by duck7000**
-  Added img url in xpath fallback part.
- Convert runtime from seconds to minutes in xmlNextJson part. it is easier to read/work with.

### CODE REVIEW

**Comment by tboothman** [comment]
I don't like this fallback business. Either one of them works or it doesn't. They have different data in them too. If i delete the xpath section the tests still pass ... what does that mean? Why did you add the img field if that section of code does nothing?

I agree seconds is nonsense and the runtimes are specified in minutes on the edit page so it makes complete sense to use that
image

**Comment by duck7000** [comment]
@tboothman 

Thanks for your comment!

Well i assumed that the fallback part actually works and does something, that's why i added the img url and because it is also added to the json part.
But i agree that it is kind of pointless to have the fallback part now i think about it and read your comment. I thought about this, especially about the fact that the output array is not consistent the same 

**And for the record i didn't add the fallback part, just add something to it.**

So what to do next? Remove the fallback part at all? I did that in my tests on my own server and it always works so the fallback part can safely be deleted i guess?

**Comment by duck7000** [comment]
I removed the fallback part completely.

**Comment by duck7000** [comment]
Mmm for this movie https://www.imdb.com/title/tt0103805/ recommendations don't work like it should, weird data is returned that not reflects the real data.
Looks like the json part does not always work while the fallback method does work fine.

i'm revert it and remove the json part as it apparently does not work reliable.

**Comment by duck7000** [comment]
The output of json is not consistent, first time the results are completely different, second time and beyond the output keeps consistent and is the same as shown on the actual webpage.

**Comment by tboothman** [comment]
Tests are failing because the year is missing from the results

**Comment by duck7000** [comment]
@tboothman

Thanks for commenting!
Sure it fails, that info is not available so the test needs adjustements.
honestly i haven't look at it, do i have to fix the test as well?
I never done that before though

Or do i add this to the method `$movie['year'] = '';`? That seems pointless though

**Comment by tboothman** [comment]
The tests are to ensure that the code continues to do what it did in the past. The year not being there showed that this was not the case.
It's fine, but it just has to be noted in the release as it's not backwards compatible. I'm not that bothered in this instance as I doubt that many people use this method and if they do it's likely they only use the id field.

**Comment by duck7000** [comment]
@tboothman 
Thanks for your comment and patients
Yeah you are right about the year, but in this case the year is not their anymore so not backwards compatible is possible . But indeed it needs to be noted.
Thanks for merging!

**Pull request merged**
