### PR TITLE
Remove short tag

### PR DESCRIPTION
**Pull request by Gavo34**

### CODE REVIEW

**Comment by tboothman** [comment]
Why? Other than consistency I don't see the problem

**Comment by duck7000** [comment]
@tboothman 
Serious?

The use of php short tags is discouraged for many many years and only available if set in the ini:

`PHP also allows for short open tag <? (which is discouraged since it is only available if enabled using the short_open_tag php.ini configuration file directive, or if PHP was configured with the --enable-short-tags option). `

And according to this website it is finally purposed for removal
https://wiki.php.net/rfc/deprecate_php_short_tags

I'm just a hobby programmer but this is something i learned not to do very quickly so i don't understand that you don't see the problem.. (i assume that you are a skilled programmer)

I agree that (for now) it's not a problem for the code to be working, but only if it is set in the ini of the used server

**Comment by tboothman** [comment]
`<?=` isn't the same as `<?`. Short tags are enabled by default but can be disabled `<?=` cannot be disabled since 5.4 and won't be removed from the language. You can argue about if `<?php echo` is better or worse than `<?=` but they both do the same thing since 5.4 and by default since before 5.4. 5.4 is very very far out of support.

**Comment by Gavo34** [comment]
Every lamp install I have used before has had it disabled by default (yum packages). so short isn't as compatible.  Its seems ott to do a pull request but that's the only option on github.

**Comment by tboothman** [comment]
You're using php 5.3?

**Comment by Gavo34** [comment]
I came across the problem in php5.3 years ago and had to update scripts,  It appears it was deprecated and then reversed, then <? dropped.

Short open tags <? will be removed. <?= continues to always be available.

**Comment by duck7000** [comment]
@tboothman 

`<?= isn't the same as <?.`
I didn't know this difference and assumed this concerned the php opening tag..
And you are absolutely right, apologies.

But for readability i would use <?php echo though

**Pull request closed without merging**
