### PR TITLE
Fix episodes() when large number of episodes in a season

### PR DESCRIPTION
**Pull request by duck7000**
- Added check if tv series season or year based
It works but i'm not absolutely sure this will cover all cases, so far tested it does.

If and how to deal with unknown season or year is not covered jet.

Perhaps code wise it could be better/smarter but main thing is will this idea work in all cases

Details are here #214

### CODE REVIEW

**Comment by duck7000** [comment]
Another thought:
Method seasons() returns 0 if series is year based, that is obviously correct but i think that there should be another method for example seasonsByYear() that returns the count based on years?

**Comment by Thomasdouscha** [comment]
> Another thought:
> Method seasons() returns 0 if series is year based, that is obviously correct but i think that there should be another method for example seasonsByYear() that returns the count based on years?

Exaclly veriy good idea  that seasonByYear()

**Comment by tboothman** [comment]
Next thing is to make some tests for shows that don't use seasons to see if this works or not, I suspect it won't as if you look at https://www.imdb.com/title/tt0388629/episodes it has a season dropdown with a 1 in it

**Comment by duck7000** [comment]
@tboothman 
That tv series actually works great, there is a blank option in seasons, i check if that blank option is there, if so get seasons by year. the question is if this is true for all tv series based on years?

But yes there should be a test, maybe someone else can get into that part? It took me a while to figure this one out.

i will try to make method seasonsByYear(), so in your application you can check if seasons is empty, if so check if seasonsByyear() not is empty and use that value.

**Comment by Thomasdouscha** [comment]
There are two true options. Based-seasons and based-years. Third option is in some part of same tvseries year-based and season-based and some unknown parts. This is incomplete and broken structure. So we should have code structure for two true options. But how to know which one? This is complicated. May be if all episedes season-based 1.st option or all apisodes based years second true option or not all episodes based years or seasons , it is smply mixed and incompleted. So that means wrong option and wil not get info episodes , just inform to user incompleted info of episodes etc. I am not well enough to help you code it. For me important esodes info and i am sharing my idea.

**Comment by duck7000** [comment]
@Thomasdouscha 
Thanks for your thoughts

I made a pull request that does basically what you want. That involves the 2 true options.
But what to do with unknown is a open question

**Comment by Thomasdouscha** [comment]
> @Thomasdouscha
> Thanks for your thoughts
> 
> This pull request does basically what you want. That involves the 2 true options.
> But what to do with unknown is an open question, sometimes it contains episodes, sometimes nothing.

There is nothing to do with unknown and mixed-based incompleted info of episodes.. In such condition code notify to users there is not right and full information of episodes. Thats it or you can login imdb site and change wrong information episodes and add missing episodes info. I did sometimes. I do not suggest you to do it.  Full and right formal information of episodes  based-seasons and based-yerars and your code will get it it iexactly well enough to me. I think for all too

**Comment by duck7000** [comment]
Some have unknown year that includes episodes, some have unknown season which is empty, some have unknown season that does include episodes etc
so in the ideal case those that have episodes should be included i guess
I'll think about it

**Comment by duck7000** [comment]
Decided to leave unknown for what it is, for some reason unknown represent -1 as value and episodes are been fetched, at least in season based.

**Comment by duck7000** [comment]
In case people don't see the value of episodes image, well i use that in my application so it has value for me.
If others don't want to use it then don't , nothing is changed just added a extra element to the output array.

It needs to be noticed in the release notes however, otherwise nobody knows of it existent.

**Pull request merged**
